# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: v2ray

on:
  schedule:
    - cron:  '* */6 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install lxml
    - name: Test with v2ray
      run: |
        python v2ray.py > v2ray.txt
    - name: commit
      run: |
        git config --global user.email conancheng@qq.com
        git config --global user.name conancheng
        git add .
        git commit -m "update" -a
        git push --force origin master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
